# Generated by Django 3.1.5 on 2021-01-12 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabels', '0003_saturated'),
    ]

    operations = [
        migrations.CreateModel(
            name='saturate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField(max_length=5)),
                ('pres', models.FloatField(max_length=5)),
                ('vol_f', models.FloatField(max_length=8)),
                ('vol_fg', models.FloatField(max_length=8)),
                ('vol_g', models.FloatField(max_length=8)),
                ('eng_f', models.FloatField(max_length=8)),
                ('eng_fg', models.FloatField(max_length=8)),
                ('eng_g', models.FloatField(max_length=8)),
                ('antal_fe', models.FloatField(max_length=8)),
                ('antal_fg', models.FloatField(max_length=8)),
                ('antal_g', models.FloatField(max_length=8)),
                ('ant_f', models.FloatField(max_length=8)),
                ('ant_fg', models.FloatField(max_length=8)),
                ('ant_g', models.FloatField(max_length=8)),
                ('material_n', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabels.material')),
                ('state_n', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabels.state')),
            ],
        ),
        migrations.DeleteModel(
            name='saturated',
        ),
    ]
